-- MySQL Script generated by MySQL Workbench
-- Sun Nov 16 23:26:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `CodDepto` INT NOT NULL,
  `NomeDepto` VARCHAR(45) NULL,
  PRIMARY KEY (`CodDepto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
  `NumDisc` INT NOT NULL,
  `NomeDisc` VARCHAR(45) NULL,
  `CreditosDisc` INT NULL,
  `Departamento_CodDepto` INT NOT NULL,
  PRIMARY KEY (`NumDisc`),
  INDEX `fk_Disciplina_Departamento_idx` (`Departamento_CodDepto` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplina_Departamento`
    FOREIGN KEY (`Departamento_CodDepto`)
    REFERENCES `mydb`.`Departamento` (`CodDepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `AnoSem` VARCHAR(45) NOT NULL,
  `SiglaTur` VARCHAR(45) NOT NULL,
  `NmaxAlunos` INT NULL,
  `Disciplina_NumDisc` INT NOT NULL,
  PRIMARY KEY (`AnoSem`, `Disciplina_NumDisc`, `SiglaTur`),
  INDEX `fk_Turma_Disciplina1_idx` (`Disciplina_NumDisc` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_Disciplina1`
    FOREIGN KEY (`Disciplina_NumDisc`)
    REFERENCES `mydb`.`Disciplina` (`NumDisc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Predio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Predio` (
  `CodPred` INT NOT NULL,
  `NomePred` VARCHAR(45) NULL,
  PRIMARY KEY (`CodPred`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sala` (
  `NumSala` INT NOT NULL,
  `Capacidade` INT NULL,
  `Predio_CodPred` INT NOT NULL,
  PRIMARY KEY (`NumSala`),
  INDEX `fk_Sala_Predio1_idx` (`Predio_CodPred` ASC) VISIBLE,
  CONSTRAINT `fk_Sala_Predio1`
    FOREIGN KEY (`Predio_CodPred`)
    REFERENCES `mydb`.`Predio` (`CodPred`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Titulacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Titulacao` (
  `CodTit` INT NOT NULL,
  `NomeTit` VARCHAR(45) NULL,
  PRIMARY KEY (`CodTit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `CodProf` INT NOT NULL,
  `NomeProf` VARCHAR(45) NULL,
  `Titulacao_CodTit` INT NOT NULL,
  `Departamento_CodDepto` INT NOT NULL,
  PRIMARY KEY (`CodProf`),
  INDEX `fk_Professor_Titulacao1_idx` (`Titulacao_CodTit` ASC) VISIBLE,
  INDEX `fk_Professor_Departamento1_idx` (`Departamento_CodDepto` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Titulacao1`
    FOREIGN KEY (`Titulacao_CodTit`)
    REFERENCES `mydb`.`Titulacao` (`CodTit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Departamento1`
    FOREIGN KEY (`Departamento_CodDepto`)
    REFERENCES `mydb`.`Departamento` (`CodDepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Horario` (
  `DiaSem` VARCHAR(45) NOT NULL,
  `HoraInicio` TIME NOT NULL,
  `NumHoras` INT NULL,
  `Turma_AnoSem` VARCHAR(45) NOT NULL,
  `Turma_SiglaTur` VARCHAR(45) NOT NULL,
  `Turma_Disciplina_NumDisc` INT NOT NULL,
  `Sala_NumSala` INT NOT NULL,
  PRIMARY KEY (`DiaSem`, `HoraInicio`, `Turma_AnoSem`, `Turma_SiglaTur`, `Turma_Disciplina_NumDisc`),
  INDEX `fk_Horario_Turma1_idx` (`Turma_AnoSem` ASC, `Turma_SiglaTur` ASC, `Turma_Disciplina_NumDisc` ASC) VISIBLE,
  INDEX `fk_Horario_Sala1_idx` (`Sala_NumSala` ASC) VISIBLE,
  CONSTRAINT `fk_Horario_Turma1`
    FOREIGN KEY (`Turma_AnoSem` , `Turma_SiglaTur` , `Turma_Disciplina_NumDisc`)
    REFERENCES `mydb`.`Turma` (`AnoSem` , `SiglaTur` , `Disciplina_NumDisc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_Sala1`
    FOREIGN KEY (`Sala_NumSala`)
    REFERENCES `mydb`.`Sala` (`NumSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PreReq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PreReq` (
  `Disciplina_NumDisc` INT NOT NULL,
  `Disciplina_NumDisReq` INT NOT NULL,
  PRIMARY KEY (`Disciplina_NumDisc`, `Disciplina_NumDisReq`),
  INDEX `fk_Disciplina_has_Disciplina_Disciplina2_idx` (`Disciplina_NumDisReq` ASC) VISIBLE,
  INDEX `fk_Disciplina_has_Disciplina_Disciplina1_idx` (`Disciplina_NumDisc` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplina_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_NumDisc`)
    REFERENCES `mydb`.`Disciplina` (`NumDisc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disciplina_has_Disciplina_Disciplina2`
    FOREIGN KEY (`Disciplina_NumDisReq`)
    REFERENCES `mydb`.`Disciplina` (`NumDisc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProfTurma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProfTurma` (
  `Turma_AnoSem` VARCHAR(45) NOT NULL,
  `Turma_SiglaTur` VARCHAR(45) NOT NULL,
  `Turma_Disciplina_NumDisc` INT NOT NULL,
  `Professor_CodProf` INT NOT NULL,
  PRIMARY KEY (`Turma_AnoSem`, `Turma_SiglaTur`, `Turma_Disciplina_NumDisc`, `Professor_CodProf`),
  INDEX `fk_Turma_has_Professor_Professor1_idx` (`Professor_CodProf` ASC) VISIBLE,
  INDEX `fk_Turma_has_Professor_Turma1_idx` (`Turma_AnoSem` ASC, `Turma_SiglaTur` ASC, `Turma_Disciplina_NumDisc` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_has_Professor_Turma1`
    FOREIGN KEY (`Turma_AnoSem` , `Turma_SiglaTur` , `Turma_Disciplina_NumDisc`)
    REFERENCES `mydb`.`Turma` (`AnoSem` , `SiglaTur` , `Disciplina_NumDisc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Professor_Professor1`
    FOREIGN KEY (`Professor_CodProf`)
    REFERENCES `mydb`.`Professor` (`CodProf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
